import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homepage from '../compos/Homepage'



export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>chatJPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">

        <Homepage />
      </main>
    </div>
  )
}
